### ISSUE TITLE
При ошибке чтения из файла программа не завершается

### ISSUE THREAD

**Issue by GordPavel** [nikitabulak/debt-calculator#2]
https://github.com/nikitabulak/debt-calculator/blob/1d2b87676391ab577edc68cd96ff1cdeb419fa62/src/calculator/DebtCalculator.java#L125

Если ошибка чтения из файла, то в консольном сообщение запишется, но программа не завершается и падает с ошибкой в другом месте

**Comment by nikitabulak** [comment]
Done
