### ISSUE TITLE
Подсчет долгов в лоб

### ISSUE THREAD

**Issue by GordPavel** [nikitabulak/debt-calculator#3]
Ты считаешь, кто кому сколько должен, прямо считая, кто за кого сколько заплатил. Думаю, что этот подход, которым мы все пользуемся в таких вещах, не совсем корректным. По сути не важно, за что ты заплатил, важна лишь разница, сколько суммарно денег ты заплатил, и на какую сумму "наел". То есть можно просуммировать дебит и кредит каждого участника, найти разницу и уже с ней что-то сделать.
При таком подходе взаиморасчеты потом будут оптимальными и логика программы будет понятнее

**Comment by nikitabulak** [comment]
Done
